#  BA1A
def PatternCount(text, pattern):
    cnt = 0
    t,p = len(text), len(pattern)
    for i in range(t):
        pcnt = 0
        for x,y in zip(text[i:i+p],pattern) :
            if x == y:
               pcnt += 1
            else:
               break
        if pcnt == p:
               cnt += 1
    return cnt

# text = 'TCGAGCCGCGCACCGCGCACTATCGCGACCGCGCACCGCGCACACGCGCGCACCGCGCACCGCGCACCCGCGCACTAGCGCGCACATTCGCGCACCGCGCACCCGCGCACGCGCGCACAGACCGCGCGCACGTGGCGCGCACCCGAGCGCGCACCGCGCACCGCGCACAACTCGCGCACCTTCATCCGCGCACCTGCGGCGCGCACCGCGCACACGCGCACACGCGCACACGCGCACACGCGCACCGCGCACATCGCGCACTCCGCGCACGTCGCGCACCTCGCGCACCAACGCGCACGTTGCGCGCACTGATTCACCGCGCACACGCGCACGCGCGCACTCGCGCACTCTGTTGTACGCGCACGGCCGCGCACTATTCTCGCGCACCGCGCACCAAACGCGCACCGCGCACACCGCGCACCGCGCACCGCGCACCGCGCACCTCGCGCACACGCGCACCGCGCACCGCGCACAGACCAAAGGCGCGCACTTCGCGCACGATGCGCGCACCCTTCGCGCACTGACCTGTCGCGCACCACGCGCACCGCGCACCGCGCACGTTACTCCGCGCACCTAACGCGCACTCGCGCACTCGCGCACGCGCGCACAACTCTCGCGCACGCGCGCACACAGTGTCGCGCACGCGCACCGCGCACGGCGCACGCGCACCGCGCACCGCGCACTACGCGCACAGGCTCGCGCACCGCGCACGTTCCTCTAGAAAACGCGCACACGATAACGCGCACACCTGCACGCGCACTTTCGCGCACCGCGCACACGCGCACCGCGCACAACGCGCGCACGCGCGCACTCGCGCGCACCGCGCACAGCGCGCACGCCGCGCACCGCGCACTCAAGCTTTAACGCGCACGGCGCGCACTTGCTTTGCTGACGTTCGCGCACTCGCGCACACGCGCACCGCGCACCGCGCAC'
# pattern = 'CGCGCACCG'
text = 'GCGCG'
pattern = 'GCG'
print(PatternCount(text, pattern))
